# Generated by Django 3.2 on 2021-04-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_component', '0002_alter_predictions_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictions',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='st_slope',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='thallium_scan_results',
        ),
        migrations.AddField(
            model_name='predictions',
            name='cp_Asymptomatic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='cp_Atypical_Angina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='cp_Non_Angina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='st_slope_DownSloping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='st_slope_Flat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='st_slope_Upsloping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='thallium_Fixed_Defect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='thallium_None',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='thallium_Normal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predictions',
            name='thallium_Reversible_Defect',
            field=models.IntegerField(default=0),
        ),
    ]
